name: CI Docker

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Clone main repository
        uses: actions/checkout@v6

      - name: Install Docker Buildx
        if: ${{ github.event.inputs.Docker == 'true' }}
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          install: true

      - name: Build and push image for amd64 and arm64 on Docker Hub
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t lifailon/lazycompose:latest \
            --push .